[build]
  base = "netlify/"
  publish = "build/site/"
  command = "node_modules/.bin/antora --pull ../site.yml"

[build.environment]
  NODE_VERSION = "8"
  BUILD_ONLY = "true"
  ANTORA_CACHE_DIR = "node_modules/.cache/antora"

[context.deploy-preview]
  command = "node_modules/.bin/antora --pull ../site.yml --url $DEPLOY_PRIME_URL"


# Redirections for component 'init'

[[redirects]]
  from = "/digitalstandards/index.html"
  to = "/digitalstandards/init/index.html?annotate=:annotate"
  query = { annotate = ":annotate" }
  status = 301
  force = false

[[redirects]]
  from = "/digitalstandards/index.html"
  to = "/digitalstandards/init/index.html"
  status = 301
  force = false

[[redirects]]
  from = "/digitalstandards/"
  to = "/digitalstandards/init/index.html?annotate=:annotate"
  query = { annotate = ":annotate" }
  status = 301
  force = false

[[redirects]]
  from = "/digitalstandards/"
  to = "/digitalstandards/init/index.html"
  status = 301
  force = false


# Redirections for other components

[[redirects]]
  from = "/digitalstandards/agile-methodologies/"
  to = "/digitalstandards/agile-methodologies/introduction.html"
  status = 301
  force = false

[[redirects]]
  from = "/digitalstandards/data-management/"
  to = "/digitalstandards/data-management/summary.html"
  status = 301
  force = false

[[redirects]]
  from = "/digitalstandards/digital-services/"
  to = "/digitalstandards/digital-services/index.html"
  status = 301
  force = false

[[redirects]]
  from = "/digitalstandards/free-soft/"
  to = "/digitalstandards/free-soft/introduction.html"
  status = 301
  force = false

[[redirects]]
  from = "/digitalstandards/glossary/"
  to = "/digitalstandards/glossary/glossary.html"
  status = 301
  force = false

[[redirects]]
  from = "/digitalstandards/ict-procurement/"
  to = "/digitalstandards/ict-procurement/context.html"
  status = 301
  force = false

[[redirects]]
  from = "/digitalstandards/innovative-procurement/"
  to = "/digitalstandards/innovative-procurement/innovating.html"
  status = 301
  force = false

[[redirects]]
  from = "/digitalstandards/tech-practices/"
  to = "/digitalstandards/tech-practices/aim-and-scope.html"
  status = 301
  force = false

[[redirects]]
  from = "/digitalstandards/tech-sovereignty/"
  to = "/digitalstandards/tech-sovereignty/introduction.html"
  status = 301
  force = false


# Redirections to latest version of each component

[[redirects]]
  from = "/digitalstandards/init/index.html"
  to = "/digitalstandards/init/0.1/index.html?annotate=:annotate"
  query = { annotate = ":annotate" }
  status = 301
  force = false

[[redirects]]
  from = "/digitalstandards/init/index.html"
  to = "/digitalstandards/init/0.1/index.html"
  status = 301
  force = false

[[redirects]]
  from = "/digitalstandards/agile-methodologies/*"
  to = "/digitalstandards/agile-methodologies/0.1/:splat"
  status = 301
  force = false

[[redirects]]
  from = "/digitalstandards/data-management/*"
  to = "/digitalstandards/data-management/0.1/:splat"
  status = 301
  force = false

[[redirects]]
  from = "/digitalstandards/digital-services/*"
  to = "/digitalstandards/digital-services/0.1/:splat"
  status = 301
  force = false

[[redirects]]
  from = "/digitalstandards/free-soft/*"
  to = "/digitalstandards/free-soft/0.2/:splat"
  status = 301
  force = false

[[redirects]]
  from = "/digitalstandards/glossary/*"
  to = "/digitalstandards/glossary/0.1/:splat"
  status = 301
  force = false

[[redirects]]
  from = "/digitalstandards/ict-procurement/*"
  to = "/digitalstandards/ict-procurement/0.1/:splat"
  status = 301
  force = false

[[redirects]]
  from = "/digitalstandards/innovative-procurement/*"
  to = "/digitalstandards/innovative-procurement/0.1/:splat"
  status = 301
  force = false

[[redirects]]
  from = "/digitalstandards/tech-practices/*"
  to = "/digitalstandards/tech-practices/0.1/:splat"
  status = 301
  force = false

[[redirects]]
  from = "/digitalstandards/tech-sovereignty/*"
  to = "/digitalstandards/tech-sovereignty/0.1/:splat"
  status = 301
  force = false
