[build]
  base = "netlify/"
  publish = "build/site/"
  command = "node_modules/.bin/antora --fetch ../site.yml"

[build.environment]
  NODE_VERSION = "10"
  BUILD_ONLY = "true"
  ANTORA_CACHE_DIR = "node_modules/.cache/antora"

[context.deploy-preview]
  command = "node_modules/.bin/antora --fetch ../site.yml --url $DEPLOY_PRIME_URL"


# Redirections for component 'init'

# [[redirects]]
#   from = "/digitalstandards/*/index.html"
#   to = "/digitalstandards/:splat/init/index.html?annotate=:annotate"
#   query = { annotate = ":annotate" }
#   status = 301
#   force = false

# [[redirects]]
#   from = "/digitalstandards/*/index.html"
#   to = "/digitalstandards/:splat/init/index.html"
#   status = 301
#   force = false

[[redirects]]
  from = "/digitalstandards/"
  to = "/digitalstandards/en/init/index.html"
  status = 301
  force = false

[[redirects]]
  from = "/digitalstandards/ca/"
  to = "/digitalstandards/ca/init/index.html"
  status = 301
  force = false

[[redirects]]
  from = "/digitalstandards/en/"
  to = "/digitalstandards/en/init/index.html"
  status = 301
  force = false

[[redirects]]
  from = "/digitalstandards/es/"
  to = "/digitalstandards/es/init/index.html"
  status = 301
  force = false

[[redirects]]
  from = "/digitalstandards/*/init/"
  to = "/digitalstandards/:splat/init/index.html"
  status = 301
  force = false


# Redirections for other components

[[redirects]]
  from = "/digitalstandards/*/agile-methodologies/"
  to = "/digitalstandards/:splat/agile-methodologies/introduction.html"
  status = 301
  force = false

[[redirects]]
  from = "/digitalstandards/*/data-management/"
  to = "/digitalstandards/:splat/data-management/summary.html"
  status = 301
  force = false

[[redirects]]
  from = "/digitalstandards/*/digital-services/"
  to = "/digitalstandards/:splat/digital-services/index.html"
  status = 301
  force = false

[[redirects]]
  from = "/digitalstandards/*/free-soft/"
  to = "/digitalstandards/:splat/free-soft/introduction.html"
  status = 301
  force = false

[[redirects]]
  from = "/digitalstandards/*/glossary/"
  to = "/digitalstandards/:splat/glossary/glossary.html"
  status = 301
  force = false

[[redirects]]
  from = "/digitalstandards/*/ict-procurement/"
  to = "/digitalstandards/:splat/ict-procurement/context.html"
  status = 301
  force = false

[[redirects]]
  from = "/digitalstandards/*/innovative-procurement/"
  to = "/digitalstandards/:splat/innovative-procurement/innovating.html"
  status = 301
  force = false

[[redirects]]
  from = "/digitalstandards/*/tech-practices/"
  to = "/digitalstandards/:splat/tech-practices/aim-and-scope.html"
  status = 301
  force = false

[[redirects]]
  from = "/digitalstandards/*/tech-sovereignty/"
  to = "/digitalstandards/:splat/tech-sovereignty/introduction.html"
  status = 301
  force = false


# Redirections to latest version of each component

[[redirects]]
  from = "/digitalstandards/ca/init/*"
  to = "/digitalstandards/ca/init/0.1/:splat"
  status = 301
  force = false

[[redirects]]
  from = "/digitalstandards/en/init/*"
  to = "/digitalstandards/en/init/0.1/:splat"
  status = 301
  force = false

[[redirects]]
  from = "/digitalstandards/es/init/*"
  to = "/digitalstandards/es/init/0.1/:splat"
  status = 301
  force = false
  
[[redirects]]
  from = "/digitalstandards/ca/agile-methodologies/*"
  to = "/digitalstandards/ca/agile-methodologies/0.1/:splat"
  status = 301
  force = false

[[redirects]]
  from = "/digitalstandards/en/agile-methodologies/*"
  to = "/digitalstandards/en/agile-methodologies/0.1/:splat"
  status = 301
  force = false

[[redirects]]
  from = "/digitalstandards/es/agile-methodologies/*"
  to = "/digitalstandards/es/agile-methodologies/0.1/:splat"
  status = 301
  force = false

[[redirects]]
  from = "/digitalstandards/ca/data-management/*"
  to = "/digitalstandards/ca/data-management/0.1/:splat"
  status = 301
  force = false

[[redirects]]
  from = "/digitalstandards/en/data-management/*"
  to = "/digitalstandards/en/data-management/0.1/:splat"
  status = 301
  force = false

[[redirects]]
  from = "/digitalstandards/es/data-management/*"
  to = "/digitalstandards/es/data-management/0.1/:splat"
  status = 301
  force = false

[[redirects]]
  from = "/digitalstandards/ca/digital-services/*"
  to = "/digitalstandards/ca/digital-services/0.1/:splat"
  status = 301
  force = false

[[redirects]]
  from = "/digitalstandards/en/digital-services/*"
  to = "/digitalstandards/en/digital-services/0.1/:splat"
  status = 301
  force = false

[[redirects]]
  from = "/digitalstandards/es/digital-services/*"
  to = "/digitalstandards/es/digital-services/0.1/:splat"
  status = 301
  force = false

[[redirects]]
  from = "/digitalstandards/ca/free-soft/*"
  to = "/digitalstandards/ca/free-soft/0.2/:splat"
  status = 301
  force = false

[[redirects]]
  from = "/digitalstandards/en/free-soft/*"
  to = "/digitalstandards/en/free-soft/0.2/:splat"
  status = 301
  force = false

[[redirects]]
  from = "/digitalstandards/es/free-soft/*"
  to = "/digitalstandards/es/free-soft/0.2/:splat"
  status = 301
  force = false

[[redirects]]
  from = "/digitalstandards/ca/glossary/*"
  to = "/digitalstandards/ca/glossary/0.1/:splat"
  status = 301
  force = false

[[redirects]]
  from = "/digitalstandards/en/glossary/*"
  to = "/digitalstandards/en/glossary/0.1/:splat"
  status = 301
  force = false

[[redirects]]
  from = "/digitalstandards/es/glossary/*"
  to = "/digitalstandards/es/glossary/0.1/:splat"
  status = 301
  force = false

[[redirects]]
  from = "/digitalstandards/ca/ict-procurement/*"
  to = "/digitalstandards/ca/ict-procurement/0.1/:splat"
  status = 301
  force = false

[[redirects]]
  from = "/digitalstandards/en/ict-procurement/*"
  to = "/digitalstandards/en/ict-procurement/0.1/:splat"
  status = 301
  force = false

[[redirects]]
  from = "/digitalstandards/es/ict-procurement/*"
  to = "/digitalstandards/es/ict-procurement/0.1/:splat"
  status = 301
  force = false

[[redirects]]
  from = "/digitalstandards/ca/innovative-procurement/*"
  to = "/digitalstandards/ca/innovative-procurement/0.1/:splat"
  status = 301
  force = false

[[redirects]]
  from = "/digitalstandards/en/innovative-procurement/*"
  to = "/digitalstandards/en/innovative-procurement/0.1/:splat"
  status = 301
  force = false

[[redirects]]
  from = "/digitalstandards/es/innovative-procurement/*"
  to = "/digitalstandards/es/innovative-procurement/0.1/:splat"
  status = 301
  force = false

[[redirects]]
  from = "/digitalstandards/manifesto/*"
  to = "/digitalstandards/manifesto/0.2/:splat"
  status = 301
  force = false

[[redirects]]
  from = "/digitalstandards/ca/tech-practices/*"
  to = "/digitalstandards/ca/tech-practices/0.1/:splat"
  status = 301
  force = false

[[redirects]]
  from = "/digitalstandards/en/tech-practices/*"
  to = "/digitalstandards/en/tech-practices/0.1/:splat"
  status = 301
  force = false

[[redirects]]
  from = "/digitalstandards/es/tech-practices/*"
  to = "/digitalstandards/es/tech-practices/0.1/:splat"
  status = 301
  force = false

[[redirects]]
  from = "/digitalstandards/ca/tech-sovereignty/*"
  to = "/digitalstandards/ca/tech-sovereignty/0.1/:splat"
  status = 301
  force = false

[[redirects]]
  from = "/digitalstandards/en/tech-sovereignty/*"
  to = "/digitalstandards/en/tech-sovereignty/0.1/:splat"
  status = 301
  force = false

[[redirects]]
  from = "/digitalstandards/es/tech-sovereignty/*"
  to = "/digitalstandards/es/tech-sovereignty/0.1/:splat"
  status = 301
  force = false
