[build]
  base = "netlify/"
  publish = "build/site/"
  command = "node_modules/.bin/antora --pull ../site.yml"

[build.environment]
  NODE_VERSION = "8"
  BUILD_ONLY = "true"
  ANTORA_CACHE_DIR = "node_modules/.cache/antora"

[context.deploy-preview]
  command = "node_modules/.bin/antora --pull ../site.yml --url $DEPLOY_PRIME_URL"


# Redirections for component 'init'

[[redirects]]
  from = "/index.html"
  to = "/init/index.html?annotate=:annotate"
  query = { annotate = ":annotate" }
  status = 301
  force = false

[[redirects]]
  from = "/index.html"
  to = "/init/index.html"
  status = 301
  force = false

[[redirects]]
  from = "/"
  to = "/init/index.html?annotate=:annotate"
  query = { annotate = ":annotate" }
  status = 301
  force = false

[[redirects]]
  from = "/"
  to = "/init/index.html"
  status = 301
  force = false


# Redirections for other components

[[redirects]]
  from = "/agile-methodologies/"
  to = "/agile-methodologies/introduction.html"
  status = 301
  force = false

[[redirects]]
  from = "/data-management/"
  to = "/data-management/summary.html"
  status = 301
  force = false

[[redirects]]
  from = "/digital-services/"
  to = "/digital-services/index.html"
  status = 301
  force = false

[[redirects]]
  from = "/free-soft/"
  to = "/free-soft/introduction.html"
  status = 301
  force = false

[[redirects]]
  from = "/glossary/"
  to = "/glossary/glossary.html"
  status = 301
  force = false

[[redirects]]
  from = "/ict-procurement/"
  to = "/ict-procurement/context.html"
  status = 301
  force = false

[[redirects]]
  from = "/innovative-procurement/"
  to = "/innovative-procurement/innovating.html"
  status = 301
  force = false

[[redirects]]
  from = "/tech-practices/"
  to = "/tech-practices/aim-and-scope.html"
  status = 301
  force = false

[[redirects]]
  from = "/tech-sovereignty/"
  to = "/tech-sovereignty/introduction.html"
  status = 301
  force = false


# Redirections to latest version of each component

[[redirects]]
  from = "/init/index.html"
  to = "/init/0.1/index.html?annotate=:annotate"
  query = { annotate = ":annotate" }
  status = 301
  force = false

[[redirects]]
  from = "/init/index.html"
  to = "/init/0.1/index.html"
  status = 301
  force = false

[[redirects]]
  from = "/agile-methodologies/*"
  to = "/agile-methodologies/0.1/:splat"
  status = 301
  force = false

[[redirects]]
  from = "/data-management/*"
  to = "/data-management/0.1/:splat"
  status = 301
  force = false

[[redirects]]
  from = "/digital-services/*"
  to = "/digital-services/0.1/:splat"
  status = 301
  force = false

[[redirects]]
  from = "/free-soft/*"
  to = "/free-soft/0.2/:splat"
  status = 301
  force = false

[[redirects]]
  from = "/glossary/*"
  to = "/glossary/0.1/:splat"
  status = 301
  force = false

[[redirects]]
  from = "/ict-procurement/*"
  to = "/ict-procurement/0.1/:splat"
  status = 301
  force = false

[[redirects]]
  from = "/innovative-procurement/*"
  to = "/innovative-procurement/0.1/:splat"
  status = 301
  force = false

[[redirects]]
  from = "/tech-practices/*"
  to = "/tech-practices/0.1/:splat"
  status = 301
  force = false

[[redirects]]
  from = "/tech-sovereignty/*"
  to = "/tech-sovereignty/0.1/:splat"
  status = 301
  force = false
