runtime:
  cache_dir: ./.cache/antora
site:
  title: Ethical Digital Standards BCN
  url: https://ajuntamentdebarcelona.github.io/ethical-digital-standards-site
  start_page: init:ROOT:index.adoc
content:
  sources:
  - url: https://github.com/AjuntamentDeBarcelona/ethical-digital-standards-site.git
    branches: [master]
    start_path: landing-page
  - url: https://github.com/AjuntamentDeBarcelona/agile-methodologies-bcn-en.git
    branches: [master]
  - url: https://github.com/AjuntamentDeBarcelona/eds-glossary-bcn-en.git
    branches: [master]
  - url: https://github.com/AjuntamentDeBarcelona/ethical-data-management-bcn-en.git
    branches: [master]
  - url: https://github.com/AjuntamentDeBarcelona/free-software-guidelines-bcn-en.git
    branches: [master]
  - url: https://github.com/AjuntamentDeBarcelona/ict-procurement-bcn-en.git
    branches: [master]
  - url: https://github.com/AjuntamentDeBarcelona/innovative-procurement-bcn-en.git
    branches: [master]
  - url: https://github.com/AjuntamentDeBarcelona/tech-practices-code-bcn-en.git
    branches: [master]
  - url: https://github.com/AjuntamentDeBarcelona/tech-sovereignty-guide-bcn-en.git
    branches: [master]
asciidoc:
  attributes:
    xrefstyle: short
#     idprefix: ''
#     idseparator: '-'
#     linkattrs: ''
#     toc: ~
#     sectnums: ~
ui:
  bundle:
    url: https://gitlab.com/gmarpons/antora-ui-default/-/jobs/artifacts/master/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
