runtime:
  cache_dir: ./.cache/antora
site:
  title: Ethical Digital Standards BCN
  url: https://ajuntamentdebarcelona.github.io/ethical-digital-standards
  start_page: free-soft:ROOT:introduction.adoc
content:
  sources:
  - url: https://github.com/gmarpons/free-software-guidelines-bcn-en.git
    branches: [master]
  # - url: https://gitlab.com/antora/demo/demo-component-b.git
  #   branches: [v2.0, v1.0]
  #   start_path: docs
asciidoc:
  attributes:
    idprefix: ''
    idseparator: '-'
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/master/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
