runtime:
  cache_dir: ./.cache/antora
site:
  title: Ethical Digital Standards
  url: ethical-digital-standards-site.netlify.com
  start_page: init:ROOT:index.adoc
content:
  sources:
  - url: https://github.com/AjuntamentDeBarcelona/ethical-digital-standards-site.git
    branches: [master]
    start_path: landing-page
  - url: https://github.com/AjuntamentDeBarcelona/agile-methodologies-bcn-en.git
    branches: [master]
  - url: https://github.com/AjuntamentdeBarcelona/digital-service-standards-bcn-en.git
    branches: [master]
  - url: https://github.com/AjuntamentDeBarcelona/eds-glossary-bcn-en.git
    branches: [master]
  - url: https://github.com/AjuntamentDeBarcelona/ethical-data-management-bcn-en.git
    branches: [master]
  - url: https://github.com/AjuntamentDeBarcelona/free-software-guidelines-bcn-en.git
    branches: [master]
  - url: https://github.com/AjuntamentDeBarcelona/ict-procurement-bcn-en.git
    branches: [master]
  - url: https://github.com/AjuntamentDeBarcelona/innovative-procurement-bcn-en.git
    branches: [master]
  - url: https://github.com/AjuntamentDeBarcelona/tech-practices-code-bcn-en.git
    branches: [master]
  - url: https://github.com/AjuntamentDeBarcelona/tech-sovereignty-guide-bcn-en.git
    branches: [master]
asciidoc:
  attributes:
    xrefstyle: short
    idprefix: ''
    idseparator: '-'
ui:
  bundle:
    url: https://github.com/AjuntamentdeBarcelona/ethical-digital-standards-ui/releases/download/latest/ui-bundle.zip
    snapshot: true
